from src.models.parameters.parameter_definition import ParameterDefinition
from src.models.parameters.parameter_validators import validate_combo_box, validate_range_and_step

CAENDT5781_CHANNEL_DEFINITIONS = {
    # Input
    "rdc_len": ParameterDefinition(
        key="rdc_len",
        name="Record Lenght (ns)",
        description="Set the length of the acquisition window (in ns)\nOnly uses board value.\nFrom 20 to 1310660\nIncrements of 20",
        group="Input",
        value_type=int,
        default=15000,
        widget_type="entry",
        choices=None,
        valid_range=(20, 1310660),
        step=20,
        hardware_name="RECLEN",
        validator=validate_range_and_step,
    ),
    "pre_trig": ParameterDefinition(
        key="pre_trig",
        name="Pre-trigger (ns)",
        description="Set the portion of the waveform acquisition window to be saved before the trigger (in ns)\nFrom 10 to 20440\nIncrements of 10",
        group="Input",
        value_type=int,
        default=5000,
        widget_type="entry",
        choices=None,
        valid_range=(10, 20440),
        step=10,
        hardware_name="CH_PRETRG",
        validator=validate_range_and_step,
    ),
    "polarity": ParameterDefinition(
        key="polarity",
        name="Polarity",
        description="Set the polarity (Negative/Positive) of the input signal to be processed by the DPP-PHA algorithm",
        group="Input",
        value_type=str,
        default='POLARITY_POSITIVE',
        widget_type="combobox",
        choices=("POLARITY_POSITIVE", "POLARITY_NEGATIVE"),
        valid_range=None,
        hardware_name="CH_POLARITY",
        validator=validate_combo_box,
    ),
    "sample_baseline": ParameterDefinition(
        key="sample_baseline",
        name="N Sample baseline",
        description="Set the number of samples used by the mean filter to calculate the input pulse baseline.\nFixed means that the baseline is not evaluated",
        group="Input",
        value_type=str,
        default='BLINE_NSMEAN_32768',
        widget_type="combobox",
        choices=(
            "BLINE_NSMEAN_FIXED",
            "BLINE_NSMEAN_16",
            "BLINE_NSMEAN_64",
            "BLINE_NSMEAN_256",
            "BLINE_NSMEAN_1024",
            "BLINE_NSMEAN_4096",
            "BLINE_NSMEAN_16384",
            "BLINE_NSMEAN_32768",
        ),
        valid_range=None,
        hardware_name="CH_BLINE_NSMEAN",
        validator=validate_combo_box,
    ),
    "dc_offset": ParameterDefinition(
        key="dc_offset",
        name="DC Offset (%)",
        description="Allows the User to adjust the baseline position of the input signal on the ADC scale. The value is expressed in percentage of the input dynamic range.\nMoving the DC Offset corresponds to moving the baseline level of the input signal upward or downward in the dynamic scale to cover the full width of the pulse itself, thus avoiding saturation.\nFrom 0 to 100\nIncrements of 0.1",
        group='Input',
        value_type=float,
        default=5.0,
        widget_type="entry",
        choices=None,
        valid_range=(0, 100),
        step=0.1,
        hardware_name="CH_DCOFFSET",
        validator=validate_range_and_step,
    ),
    "coarse_gain": ParameterDefinition(
        key="coarse_gain",
        name="Coarse gain",
        description="Allows to select the input dynamic range of each channel\nGain x1, x3, x10, x33 (corresponding to 10Vpp-3Vpp-1Vpp-0.3Vpp ranges)",
        group="Input",
        value_type=float,
        default=3.0,
        widget_type="combobox",
        choices=(
            "10",
            "3.0",
            "1.0",
            "0.3",
        ),
        valid_range=None,
        hardware_name="CH_CGAIN",
        hardware_converter=lambda v: {
            10.0: "COARSE_GAIN_X1",
            3.0: "COARSE_GAIN_X3",
            1.0: "COARSE_GAIN_X10",
            0.3: "COARSE_GAIN_X33",
        }[v],
        validator=validate_combo_box,
    ),
    # Discriminator
    "threshold": ParameterDefinition(
        key="threshold",
        name="Threshold (lsb)",
        description="Channel discriminator threshold\nThe units are in lsb (least significant bit)\n1 LSB = (Input dynamic range in Vpp)/2^(Nbit) [Volt]\nFrom 0 to 16383\nIncrements of 10",
        group="Discriminator",
        value_type=int,
        default=500,
        widget_type="entry",
        choices=None,
        valid_range=(0, 16383),
        step=10,
        hardware_name="CH_THRESHOLD",
        validator=validate_range_and_step,
    ),
    "trig_holdoff": ParameterDefinition(
        key="trig_holdoff",
        name="Trigger holdoff (ns)",
        description="Set the Trigger Holdoff width\nDuring the Trigger Holdoff Time other trigger signals are not accepted by the digitizer\nFrom 10 to 655350\nIncrements of 10",
        group="Discriminator",
        value_type=int,
        default=480,
        widget_type="entry",
        choices=None,
        valid_range=(10, 655350),
        step=10,
        hardware_name="CH_TRG_HOLDOFF",
        validator=validate_range_and_step,
    ),
    "fast_smoothing": ParameterDefinition(
        key="fast_smoothing",
        name="Fast discriminator smoothing",
        description="Defines the number of samples of a moving average filter used for the RC-CR2 signal formation\nThe RC-CR2 input signal second derivative smoothing value",
        group="Discriminator",
        value_type=str,
        default="RCCR2_SMTH_1",
        widget_type="combobox",
        choices=(
            "RCCR2_SMTH_1",
            "RCCR2_SMTH_2",
            "RCCR2_SMTH_4",
            "RCCR2_SMTH_8",
            "RCCR2_SMTH_16",
            "RCCR2_SMTH_32",
        ),
        valid_range=None,
        hardware_name="CH_RCCR2_SMOOTH",
        validator=validate_combo_box,
    ),
    "rise_time": ParameterDefinition(
        key="rise_time",
        name="Input rise time (ns)",
        description="Value set to optimize the shape of the RC-CR2 signal used to trigger the board channels\nThis parameter defines the time constant of the derivative component of the PHA fast discriminator filter\nIn case of RC-CR2 this value must be equal (or 50% more) to the input rising edge, in such a way the RC-CR2 peak value corresponds to the height of the input signal.\nFrom 10 to 40950\nIncrements of 10",
        group="Discriminator",
        value_type=int,
        default=200,
        widget_type="entry",
        choices=None,
        valid_range=(10, 40950),
        step=10,
        hardware_name="CH_RCCR2_RISE",
        validator=validate_range_and_step,
    ),
    # Trapezoid
    "trap_rise_time": ParameterDefinition(
        key="trap_rise_time",
        name="Trap. rise time (ns)",
        description="Set the Trapezoid Rise Time\nFrom 10 to 40950\nIncrements of 10",
        group="Trapezoid",
        value_type=int,
        default=5000,
        widget_type="entry",
        choices=None,
        valid_range=(10, 40950),
        step=10,
        hardware_name="CH_TRAP_TRISE",
        validator=validate_range_and_step,
    ),
    "trap_flat_top": ParameterDefinition(
        key="trap_flat_top",
        name="Trap. flat top (ns)",
        description="Set the Trapezoid Flat Top width.\nFrom 10 to 40950\nIncrements of 10",
        group="Trapezoid",
        value_type=int,
        default=1000,
        widget_type="entry",
        choices=None,
        valid_range=(10, 40950),
        step=10,
        hardware_name="CH_TRAP_TFLAT",
        validator=validate_range_and_step,
    ),
    "trap_pole_zero": ParameterDefinition(
        key="trap_pole_zero",
        name="Trap. pole zero (ns)",
        description="Set the Trapezoid Pole-Zero Cancellation. Must be set equal to the decay time of the preamplifier.\nFrom 10 to 655350\nIncrements of 10",
        group="Trapezoid",
        value_type=int,
        default=1000,
        widget_type="entry",
        choices=None,
        valid_range=(10, 655350),
        step=10,
        hardware_name="CH_TDECAY",
        validator=validate_range_and_step,
    ),
    "peaking_time": ParameterDefinition(
        key="peaking_time",
        name="Peaking time (%)",
        description="Position in percentage in the flat top region where the samples are used for the calculation of the peak height.\nThe peaking time is referred to the trigger position or to the trigger validation signal according to the trigger mode.\nIncrements of 0.1",
        group="Trapezoid",
        value_type=float,
        default=80.0,
        widget_type="entry",
        choices=None,
        valid_range=(0, 100),
        step=0.1,
        hardware_name="CH_TRAP_FTD",
        validator=validate_range_and_step,
    ),
    "samples_peak": ParameterDefinition(
        key="samples_peak",
        name="N samples peak",
        description="Corresponds to the number of samples for the averaging window of the trapezoid height calculation.\nNote: for a correct energy calculation the Peak Mean should be contained in the flat region of the Trapezoid Flat Top.",
        group="Trapezoid",
        value_type=str,
        default="PEAK_NSMEAN_1",
        widget_type="combobox",
        choices=("PEAK_NSMEAN_1", "PEAK_NSMEAN_4", "PEAK_NSMEAN_16", "PEAK_NSMEAN_64"),
        valid_range=None,
        hardware_name="CH_PEAK_NSMEAN",
        validator=validate_combo_box,
    ),
    "peak_holdoff": ParameterDefinition(
        key="peak_holdoff",
        name="Peak holdoff (ns)",
        description="The Peak Hold-off starts at the end of the trapezoid flat top and defines how close must be two trapezoids to be considered piled-up.\nZero is the case where the flat top of one trapezoid starts exactly at the end of the flat top of the previous one.\nFrom 80 to 81840\nOnly multiples of 8 are allowed",
        group="Trapezoid",
        value_type=int,
        default=960,
        widget_type="entry",
        choices=None,
        valid_range=(80, 81840),
        step=8,
        hardware_name="CH_PEAK_HOLDOFF",
        validator=validate_range_and_step,
    ),
    "energy_fine_gain": ParameterDefinition(
        key="energy_fine_gain",
        name="Energy fine gain",
        description="Allow the User to set the fine Gain.\nFrom 1 to 10\nIncrements of 0.01",
        group="Trapezoid",
        value_type=float,
        default=1.0,
        widget_type="entry",
        valid_range=(1, 10),
        step=0.01,
        hardware_name="CH_FGAIN",
        validator=validate_range_and_step,
    ),
}