from PySide6.QtCore import Qt
from PySide6.QtGui import QBrush, QColor, QPalette
from xml.etree import ElementTree
import pyqtgraph as pg
from pathlib import Path

COLORS = [
    "#000000",  # black
    "#0033CC",  # blue
    "#800080",  # purple
    "#CC0000",  # red
    "#008080",  # teal
    "#6600CC",  # violet
    "#006400",  # dark green
    "#8B0000",  # dark red
]

def generate_palette(file_path = None) -> 'QPalette':
    """
    Palette generated by "Save palette" option of Qt Designer.
    
    Adapted from code by Tuhin Srivastava. Used with permission from the author.
    
    Original source:
    https://gist.github.com/Tuhin-thinks/94df76e276243a651cb70aed0faa9c18
    
    
    Modifications by Jean-Emmanuel Chouinard:
        - Updated dependencies (PyQt5 --> PySide6)
        - Changed function name (parse_xml --> generate_palette)
    """
    def generate_brushes(brush_index):
        # required imports
        assert QColor
        assert Qt
        assert QBrush
        
        brush_style_, *rgba = brushes[brush_index]
        brush_ = eval(f"QBrush(QColor(*{rgba}))")
        brush_.setStyle(eval(f"Qt.{brush_style_}"))
        return brush_
    
    def check_or_create_brush(brush_style, *color_args):
        if (brush_style, *color_args) in brushes:
            return brushes.index((brush_style, *color_args))
        else:
            brushes.append((brush_style, *color_args))
            return len(brushes) - 1
    
    if file_path is None:
        file_path = Path(__file__).parent / "palettes" / "flashy_theme.xml"
    else:
        file_path = Path(file_path)
    
    if not file_path.exists():
        return QPalette()
    
    tree = ElementTree.parse(file_path)
    
    tree = ElementTree.parse(file_path)
    root = tree.getroot()
    
    brushes = []
    qt_brushes = []
    assign_brush_roles = {}
    
    for activeState in root:
        active_state = activeState.tag
        assign_brush_roles[active_state.title()] = {}
        
        for colorRole in activeState:
            role = colorRole.attrib['role']  # get the role for the colorRole (ex.: WindowText)
            
            brush = colorRole[0]  # get the brush element
            brushStyle = brush.attrib['brushstyle']  # get the brush style, solidPattern, ...etc
            
            color = colorRole[0][0]  # get color element for the brush
            alpha = color.attrib['alpha']  # get the color alpha value
            r, g, b, a = color[0].text, color[1].text, color[2].text, alpha  # get color values for the brush
            # checks if brush exists, or create a new brush and stores it
            index_ = check_or_create_brush(brushStyle, int(r), int(g), int(b), int(a)) # type:ignore
            
            assign_brush_roles[active_state.title()][role] = index_
    
    for br_index in range(len(brushes)):
        _brush = generate_brushes(br_index)
        qt_brushes.append(_brush)
    
    # create palette
    palette = QPalette()
    for active_state, role_dict in assign_brush_roles.items():
        for _role, _brush in role_dict.items():
            brush_x = qt_brushes[_brush]
            assert brush_x
            eval(f"palette.setBrush(QPalette.{active_state}, QPalette.{_role}, brush_x)")
    
    return palette

def get_pen(index, width:int=1):
    return pg.mkPen(COLORS[index % len(COLORS)], width=width)


FLASHy_THEME = generate_palette()

pg.setConfigOption('background', pg.mkColor(205, 175, 122))
pg.setConfigOption('foreground', FLASHy_THEME.color(QPalette.ColorRole.WindowText))